### ISSUE TITLE
tests fail on first run - pass on second 

### ISSUE THREAD

**Issue by ghost** [esl/release_poller#11]
Create rabbitmq docker instance

```
/code/common/release_poller/ docker run --detach --rm --hostname bugs-bunny --name roger_rabbit -p 5672:5672 -p 15672:15672 rabbitmq:3.7.7-management
Unable to find image 'rabbitmq:3.7.7-management' locally
3.7.7-management: Pulling from library/rabbitmq
Digest: sha256:a4ae5d7965167e593299bbc12298614f4f6e339492be21f245592994128047b9
Status: Downloaded newer image for rabbitmq:3.7.7-management
80be70ad46d4b3dc7fa6819343b98f5beeb94db3160f537939d21dbe565ca7ee
```
Run the tests - many failures : 

```
/code/common/release_poller/ mix test     ==> docker_api
..

Finished in 0.06 seconds
2 tests, 0 failures

Randomized with seed 281832
==> bugs_bunny
.......

  1) test gets connection to open channel manually (BugsBunny.Integration.ApiTest)
     test/integration/api_test.exs:70
     match (=) failed
     code:  assert {:ok, conn} = BugsBunny.get_connection(pool_id)
     right: {:error, :disconnected}
     stacktrace:
       test/integration/api_test.exs:71: (test)



  2) test reconnects to rabbitmq when a connection crashes (BugsBunny.Integration.RabbitConnectionTest)
     test/integration/rabbit_connection_test.exs:22
     match (=) failed
     code:  assert {:ok, %{pid: conn_pid}} = ConnWorker.get_connection(pid)
     right: {:error, :disconnected}
     stacktrace:
       test/integration/rabbit_connection_test.exs:28: anonymous fn/1 in BugsBunny.Integration.RabbitConnectionTest."test reconnects to rabbitmq when a connection crashes"/1
       (ex_unit) lib/ex_unit/capture_log.ex:78: ExUnit.CaptureLog.capture_log/2
       test/integration/rabbit_connection_test.exs:27: (test)


13:46:32.645 [error] [Rabbit] error reason: {:socket_closed_unexpectedly, :"connection.start"}

13:46:32.658 [error] [Rabbit] error reason: {:socket_closed_unexpectedly, :"connection.start"}


  3) test executes command with a channel (BugsBunny.Integration.ApiTest)
     test/integration/api_test.exs:45
     ** (FunctionClauseError) no function clause matching in anonymous fn/1 in BugsBunny.Integration.ApiTest."test executes command with a channel"/1

     The following arguments were given to anonymous fn/1 in BugsBunny.Integration.ApiTest."test executes command with a channel"/1:

         # 1
         {:error, :disconnected}

     code: BugsBunny.with_channel(pool_id, fn {:ok, channel} ->
     stacktrace:
       test/integration/api_test.exs:46: anonymous fn/1 in BugsBunny.Integration.ApiTest."test executes command with a channel"/1
       test/integration/api_test.exs:46: (test)



  4) test creates a new channel to when a channel crashes (BugsBunny.Integration.RabbitConnectionTest)
     test/integration/rabbit_connection_test.exs:40
     match (=) failed
     code:  assert {:ok, channel} = ConnWorker.checkout_channel(pid)
     right: {:error, :disconnected}
     stacktrace:
       test/integration/rabbit_connection_test.exs:46: anonymous fn/1 in BugsBunny.Integration.RabbitConnectionTest."test creates a new channel to when a channel crashes"/1
       (ex_unit) lib/ex_unit/capture_log.ex:78: ExUnit.CaptureLog.capture_log/2
       test/integration/rabbit_connection_test.exs:45: (test)



  5) test returns channel to pool after client actions (BugsBunny.Integration.ApiTest)
     test/integration/api_test.exs:59
     ** (FunctionClauseError) no function clause matching in anonymous fn/1 in BugsBunny.Integration.ApiTest."test returns channel to pool after client actions"/1

     The following arguments were given to anonymous fn/1 in BugsBunny.Integration.ApiTest."test returns channel to pool after client actions"/1:

         # 1
         {:error, :disconnected}

     code: BugsBunny.with_channel(pool_id, fn {:ok, _channel} ->
     stacktrace:
       test/integration/api_test.exs:63: anonymous fn/1 in BugsBunny.Integration.ApiTest."test returns channel to pool after client actions"/1
       test/integration/api_test.exs:63: (test)



  6) test returns out of channels when there aren't more channels (BugsBunny.Integration.ApiTest)
     test/integration/api_test.exs:51
     ** (FunctionClauseError) no function clause matching in anonymous fn/1 in BugsBunny.Integration.ApiTest."test returns out of channels when there aren't more channels"/1

     The following arguments were given to anonymous fn/1 in BugsBunny.Integration.ApiTest."test returns out of channels when there aren't more channels"/1:

         # 1
         {:error, :disconnected}

     code: BugsBunny.with_channel(pool_id, fn {:ok, _channel} ->
     stacktrace:
       test/integration/api_test.exs:52: anonymous fn/1 in BugsBunny.Integration.ApiTest."test returns out of channels when there aren't more channels"/1
       test/integration/api_test.exs:52: (test)



  7) test returns channel to the pool only once when there is a crash in a client using with_channel (BugsBunny.Integration.ApiTest)
     test/integration/api_test.exs:76
     No message matching {:DOWN, ^ref, :process, ^client_pid, {%{message: "die"}, _stacktrace}} after 1000ms.
     The following variables were pinned:
       ref = #Reference<0.1413091235.1600389126.159735>
       client_pid = #PID<0.474.0>
     Process mailbox:
       {:trace, #PID<0.468.0>, :receive, {:"$gen_call", {#PID<0.474.0>, #Reference<0.1413091235.1600389126.159739>}, :checkout_channel}}
       {:trace, #PID<0.468.0>, :receive, {#Reference<0.1413091235.1600389123.160741>, {:error, {:socket_closed_unexpectedly, :"connection.start"}}}}
       {:DOWN, #Reference<0.1413091235.1600389126.159735>, :process, #PID<0.474.0>, {:function_clause, [{BugsBunny.Integration.ApiTest, :"-test returns channel to the pool only once when there is a crash in a client using with_channel/1-fun-0-", [error: :disconnected], [file: 'test/integration/api_test.exs', line: 86]}, {Task.Supervised, :do_apply, 2, [file: 'lib/task/supervised.ex', line: 89]}, {:proc_lib, :init_p_do_apply, 3, [file: 'proc_lib.erl', line: 247]}]}}
     code: capture_log(fn ->
     stacktrace:
       test/integration/api_test.exs:93: anonymous fn/1 in BugsBunny.Integration.ApiTest."test returns channel to the pool only once when there is a crash in a client using with_channel"/1
       (ex_unit) lib/ex_unit/capture_log.ex:78: ExUnit.CaptureLog.capture_log/2
       test/integration/api_test.exs:79: (test)



  8) test returns channel to the pool only once when the channel closes using with_channel (BugsBunny.Integration.ApiTest)
     test/integration/api_test.exs:109
     No message matching {:DOWN, ^ref, :process, ^client_pid, :normal} after 500ms.
     The following variables were pinned:
       ref = #Reference<0.1413091235.1600389126.159820>
       client_pid = #PID<0.491.0>
     Process mailbox:
       {:trace, #PID<0.485.0>, :receive, {#Reference<0.1413091235.1600389126.159806>, {:error, {:already_started, :rabbit_common}}}}
       {:trace, #PID<0.485.0>, :receive, {#Reference<0.1413091235.1600389126.159807>, {:ok, #PID<0.488.0>, #PID<0.490.0>}}}
       {:trace, #PID<0.485.0>, :receive, {:"$gen_call", {#PID<0.491.0>, #Reference<0.1413091235.1600389126.159824>}, :checkout_channel}}
       {:trace, #PID<0.485.0>, :receive, {#Reference<0.1413091235.1600389126.159818>, {:error, {:socket_closed_unexpectedly, :"connection.start"}}}}
       {:trace, #PID<0.485.0>, :receive, {:DOWN, #Reference<0.1413091235.1600389126.159818>, :process, #PID<0.490.0>, {:shutdown, {:error, {:socket_closed_unexpectedly, :"connection.start"}}}}}
       {:DOWN, #Reference<0.1413091235.1600389126.159820>, :process, #PID<0.491.0>, {:function_clause, [{BugsBunny.Integration.ApiTest, :"-test returns channel to the pool only once when the channel closes using with_channel/1-fun-0-", [error: :disconnected], [file: 'test/integration/api_test.exs', line: 119]}]}}
     code: capture_log(fn ->
     stacktrace:
       test/integration/api_test.exs:125: anonymous fn/2 in BugsBunny.Integration.ApiTest."test returns channel to the pool only once when the channel closes using with_channel"/1
       (ex_unit) lib/ex_unit/capture_log.ex:78: ExUnit.CaptureLog.capture_log/2
       test/integration/api_test.exs:116: (test)



Finished in 1.7 seconds
15 tests, 8 failures

Randomized with seed 281832
==> domain
..................................

Finished in 8.2 seconds
34 tests, 0 failures

Randomized with seed 281832
==> repo_jobs
................

Finished in 0.3 seconds
16 tests, 0 failures

Randomized with seed 281832
==> repo_poller
.......................

Finished in 2.9 seconds
23 tests, 0 failures

Randomized with seed 281832
```

Run the tests again - tests pass : 

```
/code/common/release_poller/ mix test==> docker_api
..

Finished in 0.05 seconds
2 tests, 0 failures

Randomized with seed 43581
==> bugs_bunny
...............

Finished in 0.3 seconds
15 tests, 0 failures

Randomized with seed 43581
==> domain
..................................

Finished in 7.9 seconds
34 tests, 0 failures

Randomized with seed 43581
==> repo_jobs
................

Finished in 0.3 seconds
16 tests, 0 failures

Randomized with seed 43581
==> repo_poller
.......................

Finished in 3.1 seconds
23 tests, 0 failures

Randomized with seed 43581
```

**Comment by ghost** [comment]
Fixed 9 days ago
